const AppColors: any = {
  PRIMARY_COLOR: "#171531",
  SECONDARY_COLOR: "#3D56F0",
  COLOR_WHITE: "#FFFFFF",
  COLOR_BLACK: "#000000",
  COLOR_GRAY: "#808080",
  COLOR_5F: "#5FF5FF",
  COLOR_7D: "#7D7D7D",
};
export { AppColors };

const AppIcons: any = {
  ICON_ARROW_BLUE_DOWNWARD: "/images/arrow_blue_downward.svg",
  WRLD_LOGO_GIF: "/images/wrld_gif.gif",
  ICON_TOP_BAR_BG: "/images/tab_bg.svg",
  ICON_LOGO_BG: "/images/tab_logo_bg.svg",
  ICON_GOLDEN: "/images/golden_bg.png",
  ICON_HAMBURGER: "/images/icon_hamburger.svg",
  ICON_LOGO: "/images/logo.svg",
  DEMO_NFT: "/images/DemoNft.png",
  DEMO_NFT2: "/images/DemoNft2.png",
  Fire: "/images/Fire.png",
  Sm_Fire: "/images/Sm_Fire.png",
  Sm_Earth: "/images/Sm_Earth.png",
  Sm_Air: "/images/Sm_Air.png",
  Sm_Water: "/images/Sm_Water.png",
  Sm_General: "/images/Sm_General.png",
  HEART: "/images/Heart.png",
  DOT: "/images/Dot.png",
  NFTTYPE: "/images/NftType.png",
  Lg_Fire: "/images/Lg_Fire.png",
  OWNER_PROFILE_AVATAR: "/images/ownerProfileAvatar.png",
  COLLECTION_GD: "/images/CollectionGd.png",
  DEMO_COLLECTION: "/images/DemoCollection.png",
  WRLD_LOGO: "/images/wrldLogo.png",
  HORIZONTAL_COLLECTION_GD: "/images/HorizontalCollectionGd.png",
  ICON_BELL: "/images/icon_bell.svg",
  ICON_PROFILE: "/images/icon_profile.svg",
  VIEW_MORE: "/images/viewMore.png",
  PlayIcon: '/images/Subtract.png',
  ETHlogo: '/images/ethlogo.png',
  ICON_SEARCH: "/images/icon_search.svg",
  ICON_COPY: "/images/copy.svg",
  MODAL_SUBTRACT: "/images/ErrorModalSubtract.png", 
  DANGER_iCON:"/images/dangerIcon.png",
  PROFILE_BG_GREY: "/images/profile_bg_grey.svg",
  PROFILE_BG: "/images/profile_bg.svg",
  PROFILE_ITEM_TOP_BG: "/images/profile_item_top_bg.svg",
  PROFILE_ITEM_CENTER_BG: "/images/profile_item_center_bg.svg",
  PROFILE_ITEM_BOTTOM_BG: "/images/profile_item_bottom_bg.svg",
  PROFILE_SUBMIT: "/images/profile_submit.svg",
  TEST_IMG: "/images/test_bg.png",
  ICON_NOTIFICATION: "/images/icon_notification.svg",
  ICON_REWARDS_BG: "/images/icon_rewards_bg.svg",
  WALLET: "/images/Wallet.png",
  GUEST: "/images/Guest.png",
  ICON_FAV: "/images/icon_fav.svg",
  ICON_NOT_FAV: "/images/icon_not_fav.svg",
  backArrow: "/images/backarrow.png",
  TEST_IMAGE: "/images/test_img.png",
  ICON_SUBMIT: "/images/icon_submit.svg",
  ICON_SUBMIT_GRAY: "/images/icon_submit_gray.svg",
  ICON_COM_LOGO: "/images/company_logo.svg",
  ICON_COM_LOGO_2: "/images/company_logo_2.svg",
  BOX_BG: "/images/box_bg.svg",
  ICON_ETH: "/images/ethlogo.png",
  ICON_DROP_DOWN: "/images/drop_down_arrow.svg",
  ICON_INSTAGRAM: "/images/instagram.svg",
  ICON_TWITTER: "/images/twitter.svg",
  ICON_PROFILE_WALLET_BG: "/images/profile_wallet_bg.png",
  ICON_MINTING_BLUR_BG: "/images/minting_blur_bg.png",
  ICON_TWITTER_WHITE: "/images/twitter_white.svg",
  ICON_DISCORD: "/images/discord.svg",
  ICON_BLACK_CIRCLE: "/images/black_circle.svg",
  ICON_GENESIS_ISLAND: "/images/genesis_island_top_view.png",
}
export { AppIcons };

const AppDimens: any = {
  halfOne: 0.5,
  one: 1,
  two: 2,
  twoPFive: 2.5,
  twoPseven: 2.7,
  three: 3,
  threePthree: 3.3,
  four: 4,
  fourPFive: 4.5,
  five: 5,
  six: 6,
  seven: 7,
  eight: 8,
  nine: 9,
  ten: 10,
  twelve: 12,
  thirteen: 13,
  forteen: 14,
  fifteen: 15,
  sixteen: 16,
  seventeen: 17,
  eighteen: 18,
  ninteen: 19,
  twenty: 20,
  twentyTwo: 22,
  twentyThree: 23,
  twentyFour: 24,
  twentyFive: 25,
  thirty: 30,
  thirtyTwo: 32,
  thirtyFive: 35,
  forty: 40,
  fortyFive: 45,
  fifty: 50,
  fiftyFive: 55,
  sixty: 60,
  sixtyFive: 65,
  seventy: 70,
  seventyFive: 75,
  eighty: 80,
  eightyTwo: 82,
  eightyFive: 85,
  ninty: 90,
  nintyFive: 95,
  hundred: 100,
  oneTen: 110,
  oneTwenty: 120,
  oneTwentyFive: 125,
  oneThirty: 130,
  oneForty: 140,
  oneFortyEight: 148,
  oneFifty: 150,
  oneEighty: 180,
  oneNighttyEight: 198,
  twoHundred: 200,
  THREE_HUNDRED: 300,
  FOUR_HUNDRED: 400,
  FIVE_HUNDRED: 500,
  SIX_HUNDRED: 600,
};
export { AppDimens };

const AppTexts: any = {
  FLEX: "flex",
  WRAP: "wrap",
  CENTER: "center",
  NO_REPEAT: "no-repeat",
  NORMAL: "normal",
  UPPER_CASE: "uppercase",
  leftText: "flex-start",
  left: "left",
  rightText: "flex-end",
  textAtTop: "top",
  absolute: "absolute",
  spaceBetween: "space-between",
  NO_WRAP: "nowrap",
  bottomText: "bottom",
  boldText: "bold",
  justify: "justify",
  underline: "underline",
  COLUMN: "column",
  ROW: "row",
  flexStart: "flex-start",
  flexEnd: "flex-end",
  resizeContain: "contain",
  resizeCover: "cover",
  stretch: "stretch",
  large: "large",
  hidden: "hidden"
};
export { AppTexts };

const AppFonts: any = {
  Font_GRAND_SLANG: "GrandSlang",
  FONT_AKTIV_GROTESK_ENTENDED: "Aktiv Grotesk Extended"
}

export {AppFonts}